add_newline = false

format = """$directory$git_branch$git_status$character"""
right_format = """$python$nodejs$golang$docker_context"""

[character]
success_symbol = "[â±](green)"
error_symbol = "[â±](red)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "cyan"

[git_branch]
symbol = "î‚  "
style = "purple"

[git_status]
style = "red"

[python]
symbol = "ğŸ "
style = "yellow"
format = "[$symbol$version]($style) "

[nodejs]
symbol = "â¬¢ "
style = "green"
format = "[$symbol$version]($style) "

[docker_context]
symbol = "ğŸ³ "
style = "cyan"
format = "[$symbol]($style) "
